import { CategoryGalleryImage } from '../types';

export const SHRUBBERY_GALLERY: CategoryGalleryImage[] = [
      {
        url: "/images/optimized/IMG_7066_ewpawo.jpg",
        title: "Forsythia intermedia 'Weekend'",
        description: "Forsythia intermedia 'Weekend' je listopaden grm, ki je izjemno cenjen zaradi zgodnjega in obilnega cvetenja. Å½ivo rumeni cvetovi se pojavijo Å¡e pred listi in popolnoma prekrijejo veje.",
        details: {
          height: "40 - 60 cm",
          maxHeight: "2.5 m",
          evergreen: false,
          exposure: "Polno sonce / Polsenca",
          water: "Redno",
          blooming: "Februar - Marec",
          potSize: "19 cm (V19)",
          leafShape: "SuliÄasta",
          leafColor: "Zelena",
          flowerColor: "Å½ivo rumena",
          use: "Å½ive meje, obrobe, samostojni grm",
          minTemp: "-20Â°C",
          soil: "Rodovitna, dobro odcedna tla",
          pruning: "Po cvetenju"
        }
      },
      {
        url: "/images/optimized/IMG_7068_beh30q.jpg",
        title: "Juniperus horizontalis 'Wiltonii'",
        description: "Juniperus horizontalis 'Wiltonii' je nizek, plazeÄ zimzelen iglavec, ki tvori gosto srebrno-modro preprogo. Je ena najboljÅ¡ih rastlin za prekrivanje tal, saj se tesno oprijema podlage.",
        details: {
          height: "15 - 20 cm",
          maxHeight: "0.5 m (Å¡irina do 2.5 m)",
          evergreen: true,
          exposure: "Polno sonce",
          water: "Zmerno",
          blooming: "Ni cvetov (iglavec)",
          potSize: "19 cm (V19)",
          leafShape: "Iglasta / Luskasta",
          leafColor: "Srebrno-modra",
          flowerColor: "/",
          use: "Prekrivanje tal, skalnjaki, breÅ¾ine, grobovi",
          minTemp: "-20Â°C",
          soil: "Vse vrste tal, dobro odcedna",
          pruning: "Ni potrebno"
        }
      },
      {
        url: "/images/optimized/IMG_7070_ip3xai.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/hydrangea-paniculata-vanille-fraise-R---Renhy-.jpg"],
        title: "Hydrangea paniculata 'Vanille Fraise' (Renhy)",
        description: "Listopadni grm iz druÅ¾ine hortenzij (Hydrangeaceae). Ima pokonÄno, dobro razvejano, proÅ¾no in razvejano rast. DoseÅ¾e 2,5 metra v viÅ¡ino. Njegovi listi so temno zeleni, nazobÄani in ovalni. Cvetovi se pojavljajo v piramidalnih latnatih socvetjih, ki so kremasto beli in postopoma postajajo temno roÅ¾nati. PriporoÄljiva so rodovitna tla.",
        details: {
          height: "30 cm",
          maxHeight: "250 cm",
          evergreen: false,
          exposure: "Polsenca",
          water: "Redno, obilno poleti",
          blooming: "Junij - September",
          potSize: "22 cm",
          leafShape: "NazobÄana, ovalna",
          leafColor: "Svetlo zelena",
          flowerColor: "Bela, temno roÅ¾nata",
          use: "Gredice",
          minTemp: "-10Â°C",
          soil: "Rodovitna",
          pruning: "September"
        }
      },
      {
        url: "/images/optimized/IMG_7067_y4dgpf.jpg",
        title: "Kalistemon Laevis V19",
        description: "Zimzeleni grm iz druÅ¾ine mirtovk (Myrtaceae). Zaobljene oblike. SuliÄasti, trdi, temno zeleni listi. Njegovi znaÄilni rdeÄi cvetovi v obliki valjastih klasov se pojavljajo od junija do septembra. Cveti veÄkrat. Znan je tudi kot \"Äistilec steklenic\" zaradi cvetov v obliki Äistilca steklenic. Najraje ima normalna, dobro odcedna tla.",
        details: {
          plantType: "Grm",
          family: "Mirtove",
          potSize: "19 cm",
          leafColor: "Temno zelena",
          blooming: "Junij - September",
          evergreen: true,
          height: "30/35 cm",
          leafShape: "SuliÄast",
          flowerColor: "Å krlatno rdeÄa",
          use: "Gredica",
          exposure: "Sonce",
          soil: "Odcedna, rodovitna",
          pruning: "Oktober",
          maxHeight: "300 cm",
          minTemp: "0Â°C",
          water: "Malo"
        }
      },
      {
        url: "/images/optimized/IMG_7069_i20fe0.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/berberis-th.-harlequin.jpg-+-piccola.jpg"],
        title: "Berberis Thunbergii Harlequin V19",
        description: "Listopadni grm iz druÅ¾ine ÄeÅ¡minovk (Berberidaceae). Å iroke rasti, doseÅ¾e maksimalno viÅ¡ino okoli 90 cm. ZnaÄilni so bordo rdeÄi in beli listi ter bledo rumeni cvetovi spomladi. Idealen za grede in skupinske zasaditve, pa tudi kot samostojna rastlina. Uspeva v normalnih, rodovitnih in dobro odcednih tleh.",
        details: {
          plantType: "Grm",
          family: "ÄŒeÅ¡minovke (Berberidaceae)",
          potSize: "19 cm",
          leafColor: "Bordo rdeÄa, belo pisana",
          blooming: "April, maj",
          evergreen: false,
          height: "25/30 cm",
          leafShape: "Okrogla",
          flowerColor: "Rumena",
          use: "Gredica, skalnjak, Å¾iva meja",
          exposure: "Polsenca",
          soil: "Rodovitna",
          pruning: "Februar",
          maxHeight: "90 cm",
          minTemp: "-20Â°C",
          water: "Redno"
        }
      },
      {
        url: "/images/optimized/IMG_7071_m1yrje.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/buddleja-davidii-pink-dettaglio-000236.jpg"],
        title: "Buddleja Davidii Pink Delight V19 (Metuljnik)",
        description: "Listopadni grm iz druÅ¾ine metuljnikovk (Buddlejaceae). MoÄan grm s pokonÄno rastjo, ki doseÅ¾e maksimalno viÅ¡ino 300 cm. Cveti od julija do septembra. Imenujemo ga tudi 'metuljnik', saj med cvetenjem oddaja Äudovit vonj, ki privablja Å¡tevilne metulje in Å¾uÅ¾elke. RoÅ¾nati cvetovi so zdruÅ¾eni v latasta socvetja. Uspeva v rodovitnih tleh.",
        details: {
          plantType: "Grm",
          family: "Buddlejaceae",
          potSize: "19 cm",
          leafColor: "Svetlo zelena",
          blooming: "Junij, Julij, Avgust, September",
          evergreen: false,
          height: "40/50 cm",
          leafShape: "SuliÄasta",
          flowerColor: "RoÅ¾nata",
          use: "Gredica",
          exposure: "Sonce",
          soil: "Rodovitna",
          pruning: "Marec",
          maxHeight: "300 cm",
          minTemp: "-20Â°C",
          water: "Redno"
        }
      },
      {
        url: "/images/optimized/IMG_7074_vdivon.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/juniperus-hor-blue-chip.jpg-+-piccola.jpg"],
        title: "Juniperus horizontalis Blue Chip V19 (Brin)",
        description: "Zimzeleni iglavec iz druÅ¾ine cipresovk (Cupressaceae). Ima plazeÄo se, razpotegnjeno, talno pokrivajoÄo rast. DoseÅ¾e 20 cm v viÅ¡ino. Njegovi igliÄasti listi so intenzivne srebrno modre barve. Idealen za skalnjake in sadilnike. Najraje ima rodovitna, dobro odcedna tla.",
        details: {
          plantType: "Iglavec",
          family: "Cipresovke (Cupressaceae)",
          potSize: "19 cm",
          diameter: "25/30 cm",
          leafColor: "Modra, srebrna",
          evergreen: true,
          leafShape: "IgliÄast",
          use: "Gredica, skalnata",
          exposure: "Sonce",
          soil: "Odcedna, rodovitna",
          maxHeight: "20 cm",
          minTemp: "-30Â°C",
          water: "Redno"
        }
      },
      {
        url: "/images/optimized/IMG_7072_cifyoj.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/azalea-769531-1920.jpg"],
        title: "Azaleja Encore Sweetheart Â® V19 - ponovno cvetenje -",
        description: "Zimzeleni grm iz druÅ¾ine Ericaceae. Kompakten, srednje hitro rastoÄi, do 100 cm visok. Majhni, suliÄasti, svetlo zeleni listi. Obilno, Å¾ivo obarvano cveti spomladi, poleti in jeseni z globoko roÅ¾natimi poldvojnimi cvetovi. Najraje ima kisla tla.",
        details: {
          plantType: "Grm",
          family: "Vresovke",
          diameter: "30/35 cm",
          potSize: "19 cm",
          leafColor: "Sijajno zelena",
          blooming: "April, maj",
          evergreen: true,
          leafShape: "SuliÄast",
          flowerColor: "Vrtnica",
          use: "Gredica, skalnata",
          exposure: "Polsenca",
          soil: "Kislina, odcejena",
          pruning: "April",
          maxHeight: "100 cm",
          minTemp: "-20Â°C",
          water: "Redno"
        }
      },
      {
        url: "/images/optimized/IMG_7073_w6wqha.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/juniperus-procubens-nana-dettaglio-015186.jpg"],
        title: "Juniperus Procubens Nana V19 (brin)",
        description: "Zimzeleni iglavec iz druÅ¾ine Cupressaceae. Ima plazeÄo se, razpotegnjeno, talno pokrivajoÄo rast. DoseÅ¾e 40 cm v viÅ¡ino. Njegovi igliÄasti, koniÄasti, sivozeleni listi so idealni za skalnjake in sadilnike. Najraje ima rodovitna, dobro odcedna tla.",
        details: {
          plantType: "Iglavec",
          family: "Cupressaceae",
          diameter: "40/45 cm",
          potSize: "19 cm",
          leafColor: "Zelena, sivkasta",
          evergreen: true,
          leafShape: "IgliÄast",
          use: "Gredica, skalnata",
          exposure: "Sonce",
          soil: "Odcedna, rodovitna",
          maxHeight: "40 cm",
          minTemp: "-30Â°C",
          water: "Redno"
        }
      },
      {
        url: "/images/optimized/IMG_7075_m17psj.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/nerium-oleander.jpg"],
        title: "Nerium Oleander V19 - meÅ¡ani - (oleander)",
        description: "Zimzeleni grm iz druÅ¾ine Apocynaceae. Ima koÅ¡ato, pokonÄno rastno obliko, ki se pri dnu razveja. DoseÅ¾e 6 metrov v viÅ¡ino. Njegovi listi so usnjati, suliÄasti, sijoÄi in koniÄasti. Njegovi posamezni, lijakasti cvetovi pozno spomladi tvorijo Å¡opke in so roÅ¾nate, rumene, bele ali rdeÄe barve, odvisno od sorte. Najraje ima rodovitna, dobro odcedna tla.",
        details: {
          plantType: "Grm",
          family: "Apocinaceae",
          potSize: "19 cm",
          leafColor: "Zelena",
          blooming: "Avgust, junij, julij, maj, september",
          evergreen: true,
          height: "50/70 cm",
          leafShape: "SuliÄast",
          flowerColor: "Roza, rdeÄa, rumena, bela",
          use: "Gredica, Å¾iva meja, samotno",
          exposure: "Sonce",
          soil: "Plodna",
          pruning: "Oktober, september",
          maxHeight: "600 cm",
          minTemp: "-5Â°C",
          water: "Redno"
        }
      },
      {
        url: "/images/optimized/IMG_7076_chpvbw.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/loropetalum-chinensis-black-dettaglio-000741.jpg"],
        title: "ÄŒrni biser Loropetalum Chinensis Â® V19",
        description: "Zimzeleni grm iz druÅ¾ine Hamamelidaceae. Zanj so znaÄilna pokonÄna stebla in veje, ki veÄinoma rastejo vodoravno, v le nekaj letih pa lahko doseÅ¾e 1,5 metra viÅ¡ine. Njegovi listi so majhni, ovalni in temno rdeÄi, skoraj Ärni. Njegovi vijoliÄni cvetovi zaÄnejo cveteti aprila in cvetijo do jeseni. Idealen je za popestritev vrta, saj ga lahko uporabljate kot posamezno rastlino, v meÅ¡anih Å¾ivih mejah in na obrobah. Najraje ima hladna, rodovitna in dobro odcedna tla.",
        details: {
          plantType: "Grm",
          family: "Hamamelidae",
          diameter: "25/30 cm",
          potSize: "19 cm",
          leafColor: "Temno rdeÄa",
          blooming: "Avgust, april, junij, julij, maj, september",
          evergreen: true,
          leafShape: "Ovalna",
          flowerColor: "Roza, vijoliÄna",
          use: "Gredica, obroba",
          exposure: "Sonce",
          soil: "Odcedna, rodovitna",
          pruning: "September",
          maxHeight: "150 cm",
          minTemp: "-20Â°C",
          water: "Nizko povpraÅ¡evanje"
        }
      },
      {
        url: "/images/optimized/IMG_7077_gitdob.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/nandina-domestica-blush-pink-R---Aka-.jpg"],
        title: "Nandina Domestica Roza Blush Â® V19",
        description: "Zimzeleni grm iz druÅ¾ine Berberidaceae. Ima koÅ¡ato, gosto in izjemno dekorativno rast. PoÄasi raste in doseÅ¾e 1,2 metra v viÅ¡ino. SuliÄasti listi so Å¾ivo roÅ¾nati, preden postanejo zeleni, jeseni pa rdeÄi. Majhni, beli cvetovi zacvetijo pozimi in se spremenijo v spektakularne grozde rdeÄih jagod. PriporoÄljiva so rodovitna, dobro odcedna tla.",
        details: {
          plantType: "Grm",
          family: "ÄŒeÅ¡njake",
          diameter: "30/35 cm",
          potSize: "19 cm",
          leafColor: "Svetlo roza",
          blooming: "April, maj",
          evergreen: true,
          leafShape: "SuliÄast",
          flowerColor: "Bela",
          use: "Meja, pokrovnost tal",
          exposure: "Polsenca, sonce",
          soil: "Odcejena",
          pruning: "Junij, julij",
          maxHeight: "120 cm",
          minTemp: "-20Â°C",
          water: "Redno"
        }
      },
      {
        url: "/images/optimized/IMG_7083_nibscl.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/Berberis-Frikartii-Amstelveen--dettaglio-V19-000203.jpg"],
        title: "Berberis Frikartii Amstelveen V19",
        description: "Zimzeleni grm iz druÅ¾ine Berberidaceae. Ima poveÅ¡eno rast z pravilno kupolasto obliko, gosto s prepletenimi, trnastimi vejami. DoseÅ¾e 80 cm v viÅ¡ino. Njegovi podolgovati, sijoÄi temno zeleni listi so na spodnji strani beli. V aprilu in maju cveti rumeno. Najraje ima rodovitna, dobro odcedna tla.",
        details: {
          plantType: "Grm",
          family: "ÄŒeÅ¡njake",
          diameter: "25/30 cm",
          potSize: "19 cm",
          leafColor: "BleÅ¡ÄeÄa temno zelena, bela",
          blooming: "April, maj",
          evergreen: true,
          leafShape: "KroÅ¾iÅ¡Äe",
          flowerColor: "Rumena",
          use: "Gredica, skalnjak, Å¾iva meja",
          exposure: "Polsenca",
          soil: "Plodna",
          pruning: "Junij",
          maxHeight: "80 cm",
          minTemp: "-20Â°C",
          water: "Redno"
        }
      },
      {
        url: "/images/optimized/IMG_7078_pswymx.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/cornus-alba-sibirica-dettaglio-000356.jpg"],
        title: "Cornus Alba Sibirica Variegata V19 (Sibirski kornus)",
        description: "Listopadni grm iz druÅ¾ine Cornaceae. Ima elegantno, pokonÄno in urejeno rastno obliko, ki doseÅ¾e 2,5 metra v viÅ¡ino. Njegov znaÄilen, pozimi Å¾ivo rdeÄ les naredi veje zelo razkoÅ¡ne. Ovalni, zeleni listi z belimi pisanimi robovi, ki jeseni postanejo rdeÄi. DiÅ¡eÄi beli cvetovi maja in junija. Obrodi mesnate jagode, bogate z vitaminom C. PriporoÄljiva so rodovitna tla.",
        details: {
          plantType: "Grm",
          family: "Koruza",
          height: "40/50 cm",
          diameter: "-",
          potSize: "19 cm",
          leafColor: "Zelena z belim robom, jeseni rdeÄa",
          blooming: "Junij, maj",
          evergreen: false,
          leafShape: "EliptiÄna, jajÄasta",
          flowerColor: "Bela",
          use: "Gredica, samotna",
          exposure: "Polsenca, sonce",
          soil: "Plodna",
          pruning: "Marec, oktober",
          maxHeight: "250 cm",
          minTemp: "-30Â°C",
          water: "Redno obilno spomladi in poleti",
          trunk: "-"
        }
      },
      {
        url: "/images/optimized/IMG_7080_mxg6i8.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/ilex-altaclarensis-golden-dettaglio-000550.jpg"],
        title: "Ilex Altaclarensis Golden King V19 (bodika)",
        description: "Zimzeleni grm iz druÅ¾ine Aquifoliaceae. Ima koÅ¡ato, gosto, piramidasto obliko in poÄasi raste. DoseÅ¾e 3 metre v viÅ¡ino. Njegovi listi so rahlo bodiÄasti, zeleni in razkoÅ¡no pisani z Å¾ivo rumenim robom. Jeseni ima majhne, bele cvetove. Najraje ima kisla, dobro odcedna tla.",
        details: {
          plantType: "Grm",
          family: "Aquifoliaceae",
          height: "30/40 cm",
          diameter: "-",
          potSize: "19 cm",
          leafColor: "Svetlo rumeno obrobljeno zeleno",
          blooming: "December, november, oktober, september",
          evergreen: true,
          leafShape: "EliptiÄna, jajÄasta",
          flowerColor: "Mat bela",
          use: "Gredica, samotna",
          exposure: "Polsenca",
          soil: "Kislina, odcejena",
          pruning: "Februar, marec",
          maxHeight: "300 cm",
          minTemp: "-20Â°C",
          water: "Redno",
          trunk: "-"
        }
      },
      {
        url: "/images/optimized/IMG_7079_bkbzjq.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/viburnum-opulus-roseum-det.jpg"],
        title: "Viburnum Opulus Roseum V19 (viburnum)",
        description: "Listopadni grm iz druÅ¾ine Caprifoliaceae. Ima koÅ¡ato, kompaktno, zaobljeno obliko. DoseÅ¾e 3,5 metra v viÅ¡ino. Ima trikrpiÄne, temno zelene liste, ki se jeseni obarvajo vijoliÄno. DiÅ¡eÄi, beli cvetovi, ki se obarvajo roÅ¾nato, so zdruÅ¾eni v velike sneÅ¾ne kepe. Cveti pozno spomladi. Najraje ima hladna, rodovitna in dobro odcedna tla.",
        details: {
          plantType: "Grm",
          family: "KaprifolistiÄne",
          height: "40/50 cm",
          diameter: "-",
          potSize: "19 cm",
          leafColor: "Zelena",
          blooming: "April, maj",
          evergreen: false,
          leafShape: "Zobat, krpast",
          flowerColor: "Bela",
          use: "Gredica, Å¾iva meja",
          exposure: "Polsenca",
          soil: "Odcejena",
          pruning: "Junij",
          maxHeight: "350 cm",
          minTemp: "-30Â°C",
          water: "Redno",
          trunk: "-"
        }
      },
      {
        url: "/images/optimized/IMG_7081_wcihtj.jpg",
        additionalUrls: ["https://www.bessicapiante.it/pics/catalogo/osmanthus-goshiki.jpg"],
        title: "Osmanthus Heterophillus Goshiki (tribarvni) V19 (tribarvni osmantus)",
        description: "Zimzeleni grm iz druÅ¾ine oljk (Oleaceae). Ima gosto in kompaktno rast, je izjemno pritlikava, okrogla in poÄasi rastoÄa. DoseÅ¾e 1,5 metra v viÅ¡ino. Njeni listi so pisani v zeleni, kremni, roza in oranÅ¾ni barvi. So ovalni, globoko nazobÄani in usnjati. Jeseni pocveti z majhnimi, diÅ¡eÄimi belimi cvetovi. OdliÄen za Å¾ive meje. Najraje ima rodovitna, dobro odcedna tla.",
        details: {
          plantType: "Grm",
          family: "Oljne",
          height: "35/40 cm",
          diameter: "-",
          potSize: "19 cm",
          leafColor: "BleÅ¡ÄeÄe zelene barve z rumenimi, roÅ¾natimi in oranÅ¾nimi robovi",
          blooming: "November, oktober",
          evergreen: true,
          leafShape: "Podolgovat",
          flowerColor: "Bela",
          use: "Gredica, obroba, skalnjak",
          exposure: "Sonce",
          soil: "Odcejena",
          pruning: "Februar, junij, marec",
          maxHeight: "150 cm",
          minTemp: "-20Â°C",
          water: "Redno",
          trunk: "-"
        }
      },
      {
        url: "/images/optimized/IMG_7082_j41r4r.jpg",
        title: "Euonymus Fortunei Emerald'n Gold V19 (evonim)",
        description: "Zimzeleni grm iz druÅ¾ine trdoleskovk (Celastraceae). Ima plazeÄo se, razpotegnjeno rast. NajveÄja viÅ¡ina 25 cm. Ovalni, zeleni listi, ki so poleti rumeni, jeseni pa bronasti. Jeseni obrodi oranÅ¾ne jagode. Najraje ima rodovitna, dobro odcedna tla.",
        details: {
          plantType: "Grm",
          family: "Celastraceae",
          height: "30/35 cm",
          diameter: "20/25 cm",
          potSize: "19 cm",
          leafColor: "Zelena, zlata, bronasta jeseni",
          blooming: "-",
          evergreen: true,
          leafShape: "EliptiÄni",
          flowerColor: "-",
          use: "Gredica, skalnjak, pokrovnost tal",
          exposure: "Polsenca",
          soil: "Odcedna, rodovitna",
          pruning: "Julij, marec",
          maxHeight: "25 cm",
          minTemp: "-20Â°C",
          water: "Redno",
          trunk: "-"
        }
      },
      {
        url: "/images/optimized/IMG_7093_ohvxva.jpg",
        additionalUrls: [
          "https://www.bessicapiante.it/pics/catalogo/juniperus-squamata-blue-dettaglio-015188.jpg",
          "https://www.bessicapiante.it/pics/catalogo/juniperus-procubens-nana_3.jpg-+-piccola_3.jpg"
        ],
        title: "Juniperus Squamata Blue Star V19 (brin)",
        description: "Zimzeleni iglavec iz druÅ¾ine Cupressaceae. V mladosti je gost in kompakten, s staranjem pa postane okrogel in nepravilne oblike. PoÄasi raste in doseÅ¾e najveÄjo viÅ¡ino 90-100 cm v povpreÄju v 10-20 letih. Listje je zelo svetlo modre barve. Uporablja se kot pokrovna rastlina v gredicah in skalnjakih. Najraje ima rodovitna, dobro odcedna tla.",
        details: {
          plantType: "Iglavec",
          family: "Cupressaceae",
          height: "-",
          diameter: "25/30 cm",
          potSize: "19 cm",
          leafColor: "Modra",
          blooming: "-",
          evergreen: true,
          leafShape: "IgliÄast",
          flowerColor: "-",
          use: "Gredica, skalnata",
          exposure: "Sonce",
          soil: "Odcedna, rodovitna",
          pruning: "-",
          maxHeight: "90 cm",
          minTemp: "-30Â°C",
          water: "Redno",
          trunk: "-"
        }
      },
      {
        url: "/images/optimized/IMG_7092_xdw9ao.jpg",
        additionalUrls: [
          "https://www.bessicapiante.it/pics/catalogo/photinia-fraseri-red-dettaglio.jpg"
        ],
        title: "Photinia Fraseri Red Robin V19 (fotinija)",
        description: "Zimzeleni grm iz druÅ¾ine roÅ¾nic (Rosaceae). Ima kompakten, pokonÄen, grmast videz in hitro rast. DoseÅ¾e viÅ¡ino 6 metrov. Njegovo sijoÄe listje je poleti in pozimi zeleno. Mlade poganjke spomladi in jeseni so Äudovite, temno, Å¾ivo rdeÄe barve. Cvetovi pozno spomladi so majhni in beli, zdruÅ¾eni v velika socvetja. Idealen za Å¾ive meje, lahko pa se uporablja tudi kot samostojna rastlina ali v meÅ¡ani gredici. Zahteva dobro odcedna tla.",
        details: {
          plantType: "Grm",
          family: "Rosaceae",
          height: "90/120 cm",
          diameter: "-",
          potSize: "19 cm",
          leafColor: "Zelena, v mladosti Å¾ivo rdeÄa",
          blooming: "Junij, maj",
          evergreen: true,
          leafShape: "SuliÄast",
          flowerColor: "Bela",
          use: "Å½iva meja",
          exposure: "Sonce",
          soil: "Odcejena",
          pruning: "Junij, julij",
          maxHeight: "600 cm",
          minTemp: "-15Â°C",
          water: "Redno",
          trunk: "-"
        }
      },
      {
        url: "/images/optimized/IMG_7096_ait94q.jpg",
        additionalUrls: [
          "https://www.bessicapiante.it/pics/catalogo/eucalyptus-gunni-azura-det.jpg"
        ],
        title: "Evkaliptus Gunnii",
        description: "Zimzeleni grm iz druÅ¾ine mirtovk (Myrtaceae). PoÄasi rastoÄi in kompaktni, doseÅ¾e najveÄ 10+ metrov viÅ¡ine. Ima lepo, zaobljeno listje, ki se razlikuje od srebrne do turkizne barve. Å opki belih cvetov se pojavijo aprila in maja. Idealen kot posamezna rastlina. Najraje ima rodovitna, dobro odcedna tla. Dobra odpornost na mraz, do -20Â°C.",
        details: {
          plantType: "Grm",
          family: "Mirtove",
          height: "50 cm",
          diameter: "-",
          potSize: "30 cm ali 19 cm",
          leafColor: "Srebrno-turkizna",
          blooming: "April, maj",
          evergreen: true,
          leafShape: "SuliÄaste, okrogle",
          flowerColor: "Bela",
          use: "Gredica, samotna",
          exposure: "Sonce",
          soil: "Odcedna, rodovitna",
          pruning: "Junij",
          maxHeight: "10+ m",
          minTemp: "-20Â°C",
          water: "Redno",
          trunk: "-"
        }
      },
      {
        url: "/images/optimized/IMG_7091_esdmpg.jpg",
        additionalUrls: [
          "https://www.bessicapiante.it/pics/catalogo/013916-dettaglio.jpg"
        ],
        title: "Japonska aukuba (Crotonifolia) V19",
        description: "Zimzeleni grm iz druÅ¾ine Cornaceae. Gosta, zaobljena rast s svetlo zelenimi vejami in stebli. NajveÄja viÅ¡ina 2,5 metra. Veliki, usnjati, sijoÄi, svetlo zeleni listi z rumenimi progami. Majhni, temno rdeÄi latnati cvetovi se pojavijo spomladi, jeseni pa jim sledijo razkoÅ¡ni rdeÄi plodovi, ki ostanejo do pomladi, le na Å¾enskih primerkih. Najraje ima peÅ¡Äena in glinena tla.",
        details: {
          plantType: "Grm",
          family: "Koruza",
          height: "30/35 cm",
          diameter: "-",
          potSize: "19 cm",
          leafColor: "Zelena pikasta rumena",
          blooming: "April, marec",
          evergreen: true,
          leafShape: "Zobati, jajÄasti",
          flowerColor: "Temno rdeÄa",
          use: "Gredica, Å¾iva meja",
          exposure: "Polsenca, senca, sonce",
          soil: "Glinasta, peÅ¡Äena",
          pruning: "April, februar, marec",
          maxHeight: "250 cm",
          minTemp: "-20Â°C",
          water: "Redno",
          trunk: "-"
        }
      }
    ];

